services:
  vocab_matcher:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/pranavnbapat/vocab_matcher:latest
    container_name: vocab_matcher
    restart: always
    env_file:
      - .env
    ports:
      - "10000:10000"
    volumes:
      - hf_cache:/hf

volumes:
  hf_cache:
